---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: keycloak-tls
  namespace: keycloak
spec:
  secretName: keycloak-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kc.{{ settings.provision.domain }}
  dnsNames:
  - kc.{{ settings.provision.domain }}
  acme:
    config:
    - dns01:
        provider: route53
      domains:
      - kc.{{ settings.provision.domain }}
